### ISSUE TITLE
Modify background?

### ISSUE THREAD

**Issue by kirkins** [pubnub/eon-chart#14]
How can I change the background of a line chart? I'm looking to get something more like this:

![screenshot_2017-02-19_08-38-05](https://cloud.githubusercontent.com/assets/9503662/23102851/d0a1addc-f67e-11e6-8e91-3aebb96e93b6.png)

**Comment by ianjennings** [comment]
You can add gridlines by supplying the ```grid``` property within the c3 config in EON.

http://c3js.org/samples/grid_y_lines.html
